### ISSUE TITLE
STORY: Use a C++ Map for Key-Value pairs

### ISSUE THREAD

**Issue by abbi-gehl** [abbi-gehl/masm-enigma#2]
Much of the enigma involves a letter mapping to another letter.

Creating a simple assembly structure (.struct) would be very helpful in the implementation of both the switchboard and rotors.

**Comment by abbi-gehl** [comment]
Instead, use CPP std::map

**Comment by Harrison-Blair** [comment]
code written to populate the map of key value pairs, yet to be tested so this will remain open I think

**Comment by abbi-gehl** [comment]
WELL DONE TEAM, GREAT WORK
